name: HTML Lint

on:
  push: null
  pull_request:
    branches:
      - main
      - development

jobs:
  lint:
    runs-on: ubuntu-latest

    permissions:
      contents: read # Allow reading repository contents
      packages: read # Needed if using packages
      statuses: write # To report individual linter statuses
      
    steps:

      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Lint
        uses: super-linter/super-linter@v7.4.0
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
          # Add more configuration as needed
